# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - right_gripper_controller
    - right_arm_controller

  right_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - 3f_palm_finger_1_joint
      - 3f_finger_1_joint_1
      - 3f_finger_1_joint_2
      - 3f_finger_1_joint_3
      - 3f_palm_finger_2_joint
      - 3f_finger_2_joint_1
      - 3f_finger_2_joint_2
      - 3f_finger_2_joint_3
      - 3f_finger_middle_joint_1
      - 3f_finger_middle_joint_2
      - 3f_finger_middle_joint_3
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_A1
      - right_A2
      - right_A3
      - right_A4
      - right_A5
      - right_A6
      - right_A7
    action_ns: follow_joint_trajectory
    default: true