box_constraint:
  position_constraints:
    - constraint_region:
        primitive_poses:
          - position:
              x: 0
              y: 0
              z: 0
            orientation:
              w: 1.0
        primitives:
          - dimensions: [2, 2, 2]  # Box dimensions [x, y, z]
            type: box
      weight: 1.0
      header:
        frame_id: base_link
      link_name: 3f_link0
