# Default initial positions for iiwa7_table's ros2_control fake system

initial_positions:
  3f_finger_1_joint_1: 0
  3f_finger_1_joint_2: 0
  3f_finger_1_joint_3: 0
  3f_finger_2_joint_1: 0
  3f_finger_2_joint_2: 0
  3f_finger_2_joint_3: 0
  3f_finger_middle_joint_1: 0
  3f_finger_middle_joint_2: 0
  3f_finger_middle_joint_3: 0
  3f_palm_finger_1_joint: 0
  3f_palm_finger_2_joint: 0
  A1: 1
  A2: 0
  A3: 0
  A4: 0
  A5: 0
  A6: 0
  A7: 0
