# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    - gripper_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - 3f_palm_finger_1_joint
      - 3f_finger_1_joint_1
      - 3f_finger_1_joint_2
      - 3f_finger_1_joint_3
      - 3f_palm_finger_2_joint
      - 3f_finger_2_joint_1
      - 3f_finger_2_joint_2
      - 3f_finger_2_joint_3
      - 3f_finger_middle_joint_1
      - 3f_finger_middle_joint_2
      - 3f_finger_middle_joint_3