# Default initial positions for iiwa7's ros2_control fake system

initial_positions:
  2_A1: 0
  2_A2: 0
  2_A3: 0
  2_A4: 0
  2_A5: 0
  2_A6: 0
  2_A7: 0
  A1: 0
  A2: 0
  A3: 0
  A4: 0
  A5: 0
  A6: 0
  A7: 0