# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - kuka_left_controller
    - kuka_right_controller

  kuka_left_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
    action_ns: follow_joint_trajectory
    default: true
  kuka_right_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - 2_A1
      - 2_A2
      - 2_A3
      - 2_A4
      - 2_A5
      - 2_A6
      - 2_A7
    action_ns: follow_joint_trajectory
    default: true