# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  3f_finger_1_joint_1:
    has_velocity_limits: true
    max_velocity: 1.23
    has_acceleration_limits: false
    max_acceleration: 0
  3f_finger_1_joint_2:
    has_velocity_limits: true
    max_velocity: 1.24
    has_acceleration_limits: false
    max_acceleration: 0
  3f_finger_1_joint_3:
    has_velocity_limits: true
    max_velocity: 1.25
    has_acceleration_limits: false
    max_acceleration: 0
  3f_finger_2_joint_1:
    has_velocity_limits: true
    max_velocity: 1.23
    has_acceleration_limits: false
    max_acceleration: 0
  3f_finger_2_joint_2:
    has_velocity_limits: true
    max_velocity: 1.24
    has_acceleration_limits: false
    max_acceleration: 0
  3f_finger_2_joint_3:
    has_velocity_limits: true
    max_velocity: 1.25
    has_acceleration_limits: false
    max_acceleration: 0
  3f_finger_middle_joint_1:
    has_velocity_limits: true
    max_velocity: 1.23
    has_acceleration_limits: false
    max_acceleration: 0
  3f_finger_middle_joint_2:
    has_velocity_limits: true
    max_velocity: 1.24
    has_acceleration_limits: false
    max_acceleration: 0
  3f_finger_middle_joint_3:
    has_velocity_limits: true
    max_velocity: 1.25
    has_acceleration_limits: false
    max_acceleration: 0
  3f_palm_finger_1_joint:
    has_velocity_limits: true
    max_velocity: 1.23
    has_acceleration_limits: false
    max_acceleration: 0
  3f_palm_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 1.23
    has_acceleration_limits: false
    max_acceleration: 0
  left_A1:
    has_velocity_limits: true
    max_velocity: 1.7104226669544429
    has_acceleration_limits: false
    max_acceleration: 0
  left_A2:
    has_velocity_limits: true
    max_velocity: 1.7104226669544429
    has_acceleration_limits: false
    max_acceleration: 0
  left_A3:
    has_velocity_limits: true
    max_velocity: 1.7453292519943295
    has_acceleration_limits: false
    max_acceleration: 0
  left_A4:
    has_velocity_limits: true
    max_velocity: 2.2689280275926285
    has_acceleration_limits: false
    max_acceleration: 0
  left_A5:
    has_velocity_limits: true
    max_velocity: 2.4434609527920612
    has_acceleration_limits: false
    max_acceleration: 0
  left_A6:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  left_A7:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  left_finger_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0
  left_left_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0
  left_left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0
  left_right_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0
  left_right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0
  left_right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0
  right_A1:
    has_velocity_limits: true
    max_velocity: 1.7104226669544429
    has_acceleration_limits: false
    max_acceleration: 0
  right_A2:
    has_velocity_limits: true
    max_velocity: 1.7104226669544429
    has_acceleration_limits: false
    max_acceleration: 0
  right_A3:
    has_velocity_limits: true
    max_velocity: 1.7453292519943295
    has_acceleration_limits: false
    max_acceleration: 0
  right_A4:
    has_velocity_limits: true
    max_velocity: 2.2689280275926285
    has_acceleration_limits: false
    max_acceleration: 0
  right_A5:
    has_velocity_limits: true
    max_velocity: 2.4434609527920612
    has_acceleration_limits: false
    max_acceleration: 0
  right_A6:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  right_A7:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0