# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - right_arm_controller
    - left_arm_controller

  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_A1
      - right_A2
      - right_A3
      - right_A4
      - right_A5
      - right_A6
      - right_A7
    action_ns: follow_joint_trajectory
    default: true
  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_A1
      - left_A2
      - left_A3
      - left_A4
      - left_A5
      - left_A6
      - left_A7
    action_ns: follow_joint_trajectory
    default: true